/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AgendamentoTokenRouteImport } from './routes/agendamento/$token'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAssinaturaRouteImport } from './routes/_authenticated/app.assinatura'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app.clientes'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppFaturamentoRouteImport } from './routes/_authenticated/app.faturamento'
import { Route as AuthenticatedAppProdutosRouteImport } from './routes/_authenticated/app.produtos'
import { Route as AuthenticatedAppProfissionaisRouteImport } from './routes/_authenticated/app.profissionais'
import { Route as AuthenticatedAppServicosRouteImport } from './routes/_authenticated/app.servicos'
import { Route as AuthenticatedMasterPagamentosRouteImport } from './routes/_authenticated/master.pagamentos'
import { Route as AuthenticatedMasterPlanosRouteImport } from './routes/_authenticated/master.planos'
import { Route as ApiPublicCronBillingRouteImport } from './routes/api/public/cron/billing'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AgendamentoTokenRoute = AgendamentoTokenRouteImport.update({
  id: '/agendamento/$token',
  path: '/agendamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssinaturaRoute =
  AuthenticatedAppAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFaturamentoRoute =
  AuthenticatedAppFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProdutosRoute =
  AuthenticatedAppProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfissionaisRoute =
  AuthenticatedAppProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppServicosRoute =
  AuthenticatedAppServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedMasterPagamentosRoute =
  AuthenticatedMasterPagamentosRouteImport.update({
    id: '/master/pagamentos',
    path: '/master/pagamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterPlanosRoute =
  AuthenticatedMasterPlanosRouteImport.update({
    id: '/master/planos',
    path: '/master/planos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronBillingRoute = ApiPublicCronBillingRouteImport.update({
  id: '/api/public/cron/billing',
  path: '/api/public/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/app/assinatura': typeof AuthenticatedAppAssinaturaRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/faturamento': typeof AuthenticatedAppFaturamentoRoute
  '/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/master/pagamentos': typeof AuthenticatedMasterPagamentosRoute
  '/master/planos': typeof AuthenticatedMasterPlanosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/app/assinatura': typeof AuthenticatedAppAssinaturaRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/faturamento': typeof AuthenticatedAppFaturamentoRoute
  '/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/master/pagamentos': typeof AuthenticatedMasterPagamentosRoute
  '/master/planos': typeof AuthenticatedMasterPlanosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/app/assinatura': typeof AuthenticatedAppAssinaturaRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/faturamento': typeof AuthenticatedAppFaturamentoRoute
  '/_authenticated/app/produtos': typeof AuthenticatedAppProdutosRoute
  '/_authenticated/app/profissionais': typeof AuthenticatedAppProfissionaisRoute
  '/_authenticated/app/servicos': typeof AuthenticatedAppServicosRoute
  '/_authenticated/master/pagamentos': typeof AuthenticatedMasterPagamentosRoute
  '/_authenticated/master/planos': typeof AuthenticatedMasterPlanosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/cadastro'
    | '/app'
    | '/agendamento/$token'
    | '/convite/$token'
    | '/app/assinatura'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/faturamento'
    | '/app/produtos'
    | '/app/profissionais'
    | '/app/servicos'
    | '/master/pagamentos'
    | '/master/planos'
    | '/app/'
    | '/api/public/cron/billing'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/cadastro'
    | '/agendamento/$token'
    | '/convite/$token'
    | '/app/assinatura'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/faturamento'
    | '/app/produtos'
    | '/app/profissionais'
    | '/app/servicos'
    | '/master/pagamentos'
    | '/master/planos'
    | '/app'
    | '/api/public/cron/billing'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/cadastro'
    | '/_authenticated/app'
    | '/agendamento/$token'
    | '/convite/$token'
    | '/_authenticated/app/assinatura'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/faturamento'
    | '/_authenticated/app/produtos'
    | '/_authenticated/app/profissionais'
    | '/_authenticated/app/servicos'
    | '/_authenticated/master/pagamentos'
    | '/_authenticated/master/planos'
    | '/_authenticated/app/'
    | '/api/public/cron/billing'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  AgendamentoTokenRoute: typeof AgendamentoTokenRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ApiPublicCronBillingRoute: typeof ApiPublicCronBillingRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/agendamento/$token': {
      id: '/agendamento/$token'
      path: '/agendamento/$token'
      fullPath: '/agendamento/$token'
      preLoaderRoute: typeof AgendamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assinatura': {
      id: '/_authenticated/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AuthenticatedAppAssinaturaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/faturamento': {
      id: '/_authenticated/app/faturamento'
      path: '/faturamento'
      fullPath: '/app/faturamento'
      preLoaderRoute: typeof AuthenticatedAppFaturamentoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/produtos': {
      id: '/_authenticated/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AuthenticatedAppProdutosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profissionais': {
      id: '/_authenticated/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AuthenticatedAppProfissionaisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/servicos': {
      id: '/_authenticated/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AuthenticatedAppServicosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/master/pagamentos': {
      id: '/_authenticated/master/pagamentos'
      path: '/master/pagamentos'
      fullPath: '/master/pagamentos'
      preLoaderRoute: typeof AuthenticatedMasterPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/planos': {
      id: '/_authenticated/master/planos'
      path: '/master/planos'
      fullPath: '/master/planos'
      preLoaderRoute: typeof AuthenticatedMasterPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/billing': {
      id: '/api/public/cron/billing'
      path: '/api/public/cron/billing'
      fullPath: '/api/public/cron/billing'
      preLoaderRoute: typeof ApiPublicCronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssinaturaRoute: typeof AuthenticatedAppAssinaturaRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppFaturamentoRoute: typeof AuthenticatedAppFaturamentoRoute
  AuthenticatedAppProdutosRoute: typeof AuthenticatedAppProdutosRoute
  AuthenticatedAppProfissionaisRoute: typeof AuthenticatedAppProfissionaisRoute
  AuthenticatedAppServicosRoute: typeof AuthenticatedAppServicosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssinaturaRoute: AuthenticatedAppAssinaturaRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppFaturamentoRoute: AuthenticatedAppFaturamentoRoute,
  AuthenticatedAppProdutosRoute: AuthenticatedAppProdutosRoute,
  AuthenticatedAppProfissionaisRoute: AuthenticatedAppProfissionaisRoute,
  AuthenticatedAppServicosRoute: AuthenticatedAppServicosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedMasterPagamentosRoute: typeof AuthenticatedMasterPagamentosRoute
  AuthenticatedMasterPlanosRoute: typeof AuthenticatedMasterPlanosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedMasterPagamentosRoute: AuthenticatedMasterPagamentosRoute,
  AuthenticatedMasterPlanosRoute: AuthenticatedMasterPlanosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  AgendamentoTokenRoute: AgendamentoTokenRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ApiPublicCronBillingRoute: ApiPublicCronBillingRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
