-- Complete the canonical global service catalog: 20 segments x 15 templates.
-- Existing tenant services are never modified or deleted. Incorrect/obsolete global
-- suggestions are deactivated, while canonical templates are inserted idempotently.
BEGIN;

CREATE TEMP TABLE _canonical_service_catalog (
  segment_slug text NOT NULL,
  name text NOT NULL,
  duration_minutes integer NOT NULL,
  PRIMARY KEY (segment_slug, name)
) ON COMMIT DROP;

INSERT INTO _canonical_service_catalog (segment_slug, name, duration_minutes)
VALUES
  ('barbearia', 'Corte masculino', 30),
  ('barbearia', 'Corte + barba', 60),
  ('barbearia', 'Barba', 30),
  ('barbearia', 'Corte infantil', 30),
  ('barbearia', 'Pezinho', 15),
  ('barbearia', 'Sobrancelha', 15),
  ('barbearia', 'Pigmentação', 30),
  ('barbearia', 'Platinado', 120),
  ('barbearia', 'Luzes', 120),
  ('barbearia', 'Coloração', 90),
  ('barbearia', 'Relaxamento capilar', 90),
  ('barbearia', 'Hidratação capilar', 30),
  ('barbearia', 'Lavagem + finalização', 20),
  ('barbearia', 'Corte + pigmentação', 60),
  ('barbearia', 'Corte + barba + sobrancelha', 75),
  ('salao-de-beleza', 'Corte feminino', 60),
  ('salao-de-beleza', 'Corte masculino', 30),
  ('salao-de-beleza', 'Corte infantil', 30),
  ('salao-de-beleza', 'Escova', 45),
  ('salao-de-beleza', 'Escova modelada', 60),
  ('salao-de-beleza', 'Hidratação', 45),
  ('salao-de-beleza', 'Reconstrução capilar', 60),
  ('salao-de-beleza', 'Progressiva', 180),
  ('salao-de-beleza', 'Relaxamento', 120),
  ('salao-de-beleza', 'Coloração', 120),
  ('salao-de-beleza', 'Mechas', 180),
  ('salao-de-beleza', 'Luzes', 180),
  ('salao-de-beleza', 'Penteado', 90),
  ('salao-de-beleza', 'Finalização', 30),
  ('salao-de-beleza', 'Tratamento capilar', 60),
  ('manicure-pedicure', 'Manicure', 30),
  ('manicure-pedicure', 'Pedicure', 45),
  ('manicure-pedicure', 'Manicure + pedicure', 75),
  ('manicure-pedicure', 'Esmaltação comum', 30),
  ('manicure-pedicure', 'Esmaltação em gel', 60),
  ('manicure-pedicure', 'Alongamento de unhas', 120),
  ('manicure-pedicure', 'Manutenção de alongamento', 90),
  ('manicure-pedicure', 'Fibra de vidro', 150),
  ('manicure-pedicure', 'Manutenção de fibra', 90),
  ('manicure-pedicure', 'Blindagem', 60),
  ('manicure-pedicure', 'Nail art', 30),
  ('manicure-pedicure', 'Francesinha', 30),
  ('manicure-pedicure', 'Spa dos pés', 45),
  ('manicure-pedicure', 'Remoção de alongamento', 45),
  ('manicure-pedicure', 'Remoção de esmaltação em gel', 30),
  ('estetica', 'Limpeza de pele', 60),
  ('estetica', 'Limpeza de pele profunda', 90),
  ('estetica', 'Peeling', 45),
  ('estetica', 'Drenagem linfática', 60),
  ('estetica', 'Massagem modeladora', 60),
  ('estetica', 'Radiofrequência', 60),
  ('estetica', 'Criolipólise', 90),
  ('estetica', 'Ultrassom estético', 45),
  ('estetica', 'Microagulhamento', 90),
  ('estetica', 'Design corporal', 60),
  ('estetica', 'Tratamento facial', 60),
  ('estetica', 'Tratamento para acne', 60),
  ('estetica', 'Tratamento para manchas', 60),
  ('estetica', 'Depilação facial', 30),
  ('estetica', 'Depilação corporal', 60),
  ('massagem-terapias', 'Massagem relaxante', 60),
  ('massagem-terapias', 'Massagem terapêutica', 60),
  ('massagem-terapias', 'Massagem desportiva', 60),
  ('massagem-terapias', 'Shiatsu', 60),
  ('massagem-terapias', 'Reflexologia', 45),
  ('massagem-terapias', 'Drenagem linfática', 60),
  ('massagem-terapias', 'Massagem modeladora', 60),
  ('massagem-terapias', 'Massagem com pedras quentes', 90),
  ('massagem-terapias', 'Massagem aromática', 60),
  ('massagem-terapias', 'Liberação miofascial', 60),
  ('massagem-terapias', 'Reiki', 60),
  ('massagem-terapias', 'Ventosaterapia', 45),
  ('massagem-terapias', 'Auriculoterapia', 30),
  ('massagem-terapias', 'Terapia corporal', 60),
  ('massagem-terapias', 'Sessão terapêutica', 60),
  ('pet-shop-banho-tosa', 'Banho pequeno porte', 45),
  ('pet-shop-banho-tosa', 'Banho médio porte', 60),
  ('pet-shop-banho-tosa', 'Banho grande porte', 90),
  ('pet-shop-banho-tosa', 'Banho + tosa higiênica', 75),
  ('pet-shop-banho-tosa', 'Tosa higiênica', 45),
  ('pet-shop-banho-tosa', 'Tosa completa', 90),
  ('pet-shop-banho-tosa', 'Tosa na tesoura', 120),
  ('pet-shop-banho-tosa', 'Desembolo', 60),
  ('pet-shop-banho-tosa', 'Corte de unhas', 15),
  ('pet-shop-banho-tosa', 'Limpeza de ouvidos', 15),
  ('pet-shop-banho-tosa', 'Escovação dentária', 15),
  ('pet-shop-banho-tosa', 'Hidratação de pelos', 30),
  ('pet-shop-banho-tosa', 'Banho terapêutico', 60),
  ('pet-shop-banho-tosa', 'Escovação', 30),
  ('pet-shop-banho-tosa', 'Spa pet', 90),
  ('clinica-odontologica', 'Avaliação odontológica', 30),
  ('clinica-odontologica', 'Consulta odontológica', 45),
  ('clinica-odontologica', 'Limpeza dental', 60),
  ('clinica-odontologica', 'Profilaxia', 60),
  ('clinica-odontologica', 'Clareamento dental', 90),
  ('clinica-odontologica', 'Avaliação ortodôntica', 30),
  ('clinica-odontologica', 'Manutenção ortodôntica', 30),
  ('clinica-odontologica', 'Restauração', 60),
  ('clinica-odontologica', 'Extração', 60),
  ('clinica-odontologica', 'Tratamento de canal', 90),
  ('clinica-odontologica', 'Aplicação de flúor', 30),
  ('clinica-odontologica', 'Radiografia odontológica', 30),
  ('clinica-odontologica', 'Moldagem odontológica', 30),
  ('clinica-odontologica', 'Consulta de retorno', 30),
  ('clinica-odontologica', 'Avaliação estética dental', 45),
  ('personal-trainer-academia', 'Avaliação física', 60),
  ('personal-trainer-academia', 'Treino individual', 60),
  ('personal-trainer-academia', 'Treino funcional', 60),
  ('personal-trainer-academia', 'Consultoria esportiva', 60),
  ('personal-trainer-academia', 'Avaliação de composição corporal', 45),
  ('personal-trainer-academia', 'Treino para emagrecimento', 60),
  ('personal-trainer-academia', 'Treino de força', 60),
  ('personal-trainer-academia', 'Treino de condicionamento', 60),
  ('personal-trainer-academia', 'Treino para iniciantes', 60),
  ('personal-trainer-academia', 'Treino para corrida', 60),
  ('personal-trainer-academia', 'Acompanhamento mensal', 60),
  ('personal-trainer-academia', 'Reavaliação física', 45),
  ('personal-trainer-academia', 'Planejamento de treino', 60),
  ('personal-trainer-academia', 'Aula experimental', 60),
  ('personal-trainer-academia', 'Sessão online', 60),
  ('yoga-pilates', 'Aula de Yoga', 60),
  ('yoga-pilates', 'Aula de Pilates', 60),
  ('yoga-pilates', 'Aula individual de Yoga', 60),
  ('yoga-pilates', 'Aula individual de Pilates', 60),
  ('yoga-pilates', 'Avaliação de Pilates', 45),
  ('yoga-pilates', 'Aula experimental', 60),
  ('yoga-pilates', 'Yoga para iniciantes', 60),
  ('yoga-pilates', 'Yoga avançado', 60),
  ('yoga-pilates', 'Pilates para iniciantes', 60),
  ('yoga-pilates', 'Pilates avançado', 60),
  ('yoga-pilates', 'Aula de mobilidade', 45),
  ('yoga-pilates', 'Aula de alongamento', 45),
  ('yoga-pilates', 'Sessão de respiração', 30),
  ('yoga-pilates', 'Aula online', 60),
  ('yoga-pilates', 'Reavaliação', 45),
  ('sobrancelhas-cilios', 'Design de sobrancelhas', 30),
  ('sobrancelhas-cilios', 'Design + henna', 45),
  ('sobrancelhas-cilios', 'Henna', 30),
  ('sobrancelhas-cilios', 'Brow lamination', 60),
  ('sobrancelhas-cilios', 'Micropigmentação', 120),
  ('sobrancelhas-cilios', 'Manutenção de micropigmentação', 90),
  ('sobrancelhas-cilios', 'Lifting de cílios', 60),
  ('sobrancelhas-cilios', 'Extensão de cílios', 120),
  ('sobrancelhas-cilios', 'Manutenção de extensão', 90),
  ('sobrancelhas-cilios', 'Volume brasileiro', 120),
  ('sobrancelhas-cilios', 'Volume russo', 150),
  ('sobrancelhas-cilios', 'Mega volume', 180),
  ('sobrancelhas-cilios', 'Remoção de extensão', 30),
  ('sobrancelhas-cilios', 'Lash botox', 60),
  ('sobrancelhas-cilios', 'Design masculino', 30),
  ('maquiagem', 'Maquiagem social', 60),
  ('maquiagem', 'Maquiagem para festa', 90),
  ('maquiagem', 'Maquiagem para casamento', 120),
  ('maquiagem', 'Maquiagem para noiva', 150),
  ('maquiagem', 'Maquiagem para madrinha', 90),
  ('maquiagem', 'Maquiagem para formatura', 90),
  ('maquiagem', 'Maquiagem artística', 120),
  ('maquiagem', 'Maquiagem para ensaio fotográfico', 90),
  ('maquiagem', 'Maquiagem express', 30),
  ('maquiagem', 'Maquiagem masculina', 45),
  ('maquiagem', 'Aula de automaquiagem', 120),
  ('maquiagem', 'Produção completa', 120),
  ('maquiagem', 'Teste de maquiagem para noiva', 90),
  ('maquiagem', 'Maquiagem infantil', 45),
  ('maquiagem', 'Retoque de maquiagem', 30),
  ('spa', 'Spa relaxante', 90),
  ('spa', 'Day Spa', 180),
  ('spa', 'Banho relaxante', 60),
  ('spa', 'Ritual corporal', 90),
  ('spa', 'Esfoliação corporal', 60),
  ('spa', 'Hidratação corporal', 60),
  ('spa', 'Massagem relaxante', 60),
  ('spa', 'Massagem com pedras quentes', 90),
  ('spa', 'Banho de ofurô', 60),
  ('spa', 'Spa dos pés', 45),
  ('spa', 'Spa das mãos', 45),
  ('spa', 'Tratamento facial', 60),
  ('spa', 'Ritual aromático', 60),
  ('spa', 'Experiência para casal', 120),
  ('spa', 'Pacote relaxamento', 180),
  ('clinica-consultorio', 'Consulta inicial', 60),
  ('clinica-consultorio', 'Consulta de retorno', 30),
  ('clinica-consultorio', 'Avaliação', 45),
  ('clinica-consultorio', 'Atendimento particular', 60),
  ('clinica-consultorio', 'Teleconsulta', 60),
  ('clinica-consultorio', 'Acompanhamento', 45),
  ('clinica-consultorio', 'Avaliação completa', 60),
  ('clinica-consultorio', 'Retorno de avaliação', 30),
  ('clinica-consultorio', 'Orientação', 45),
  ('clinica-consultorio', 'Procedimento', 60),
  ('clinica-consultorio', 'Atendimento especializado', 60),
  ('clinica-consultorio', 'Avaliação preventiva', 60),
  ('clinica-consultorio', 'Consulta de rotina', 45),
  ('clinica-consultorio', 'Revisão de tratamento', 45),
  ('clinica-consultorio', 'Atendimento online', 60),
  ('fisioterapia', 'Avaliação fisioterapêutica', 60),
  ('fisioterapia', 'Sessão de fisioterapia', 60),
  ('fisioterapia', 'Fisioterapia ortopédica', 60),
  ('fisioterapia', 'Fisioterapia esportiva', 60),
  ('fisioterapia', 'Fisioterapia respiratória', 60),
  ('fisioterapia', 'Fisioterapia neurológica', 60),
  ('fisioterapia', 'Pilates terapêutico', 60),
  ('fisioterapia', 'RPG', 60),
  ('fisioterapia', 'Liberação miofascial', 60),
  ('fisioterapia', 'Terapia manual', 60),
  ('fisioterapia', 'Reabilitação pós-operatória', 60),
  ('fisioterapia', 'Reabilitação esportiva', 60),
  ('fisioterapia', 'Avaliação postural', 45),
  ('fisioterapia', 'Sessão de retorno', 45),
  ('fisioterapia', 'Atendimento domiciliar', 60),
  ('psicologia', 'Primeira consulta', 60),
  ('psicologia', 'Psicoterapia individual', 50),
  ('psicologia', 'Psicoterapia de casal', 60),
  ('psicologia', 'Psicoterapia familiar', 60),
  ('psicologia', 'Sessão de acompanhamento', 50),
  ('psicologia', 'Avaliação psicológica', 60),
  ('psicologia', 'Orientação profissional', 60),
  ('psicologia', 'Aconselhamento', 50),
  ('psicologia', 'Atendimento online', 50),
  ('psicologia', 'Sessão infantil', 50),
  ('psicologia', 'Sessão adolescente', 50),
  ('psicologia', 'Sessão de retorno', 50),
  ('psicologia', 'Avaliação inicial', 60),
  ('psicologia', 'Orientação parental', 60),
  ('psicologia', 'Atendimento psicológico', 50),
  ('joalheria-servicos-especializados', 'Avaliação de joia', 30),
  ('joalheria-servicos-especializados', 'Ajuste de anel', 60),
  ('joalheria-servicos-especializados', 'Ajuste de pulseira', 45),
  ('joalheria-servicos-especializados', 'Ajuste de corrente', 45),
  ('joalheria-servicos-especializados', 'Polimento de joia', 60),
  ('joalheria-servicos-especializados', 'Limpeza de joia', 30),
  ('joalheria-servicos-especializados', 'Gravação', 60),
  ('joalheria-servicos-especializados', 'Conserto de joia', 90),
  ('joalheria-servicos-especializados', 'Solda', 90),
  ('joalheria-servicos-especializados', 'Troca de pedra', 90),
  ('joalheria-servicos-especializados', 'Avaliação de relógio', 30),
  ('joalheria-servicos-especializados', 'Manutenção de relógio', 120),
  ('joalheria-servicos-especializados', 'Personalização de joia', 60),
  ('joalheria-servicos-especializados', 'Orçamento personalizado', 30),
  ('joalheria-servicos-especializados', 'Retirada/entrega de serviço', 15),
  ('estetica-automotiva', 'Lavagem simples', 60),
  ('estetica-automotiva', 'Lavagem completa', 90),
  ('estetica-automotiva', 'Higienização interna', 120),
  ('estetica-automotiva', 'Higienização de bancos', 120),
  ('estetica-automotiva', 'Polimento', 240),
  ('estetica-automotiva', 'Polimento técnico', 300),
  ('estetica-automotiva', 'Enceramento', 90),
  ('estetica-automotiva', 'Cristalização', 180),
  ('estetica-automotiva', 'Vitrificação', 300),
  ('estetica-automotiva', 'Limpeza de motor', 90),
  ('estetica-automotiva', 'Limpeza de estofados', 120),
  ('estetica-automotiva', 'Descontaminação de pintura', 120),
  ('estetica-automotiva', 'Revitalização de plásticos', 90),
  ('estetica-automotiva', 'Lavagem detalhada', 180),
  ('estetica-automotiva', 'Detalhamento completo', 360),
  ('servicos-de-limpeza', 'Limpeza residencial', 180),
  ('servicos-de-limpeza', 'Limpeza comercial', 240),
  ('servicos-de-limpeza', 'Limpeza pesada', 300),
  ('servicos-de-limpeza', 'Limpeza pós-obra', 360),
  ('servicos-de-limpeza', 'Limpeza de escritório', 180),
  ('servicos-de-limpeza', 'Limpeza de apartamento', 180),
  ('servicos-de-limpeza', 'Limpeza de casa', 240),
  ('servicos-de-limpeza', 'Limpeza de vidros', 120),
  ('servicos-de-limpeza', 'Limpeza de estofados', 120),
  ('servicos-de-limpeza', 'Limpeza de tapetes', 120),
  ('servicos-de-limpeza', 'Higienização', 180),
  ('servicos-de-limpeza', 'Limpeza de cozinha', 120),
  ('servicos-de-limpeza', 'Limpeza de banheiro', 90),
  ('servicos-de-limpeza', 'Organização residencial', 180),
  ('servicos-de-limpeza', 'Serviço de limpeza personalizado', 180),
  ('fotografia', 'Ensaio individual', 60),
  ('fotografia', 'Ensaio casal', 90),
  ('fotografia', 'Ensaio família', 120),
  ('fotografia', 'Ensaio gestante', 120),
  ('fotografia', 'Ensaio infantil', 60),
  ('fotografia', 'Ensaio profissional', 90),
  ('fotografia', 'Ensaio externo', 120),
  ('fotografia', 'Ensaio estúdio', 90),
  ('fotografia', 'Fotografia de produto', 120),
  ('fotografia', 'Cobertura de evento', 180),
  ('fotografia', 'Fotografia corporativa', 120),
  ('fotografia', 'Retrato profissional', 60),
  ('fotografia', 'Fotografia para redes sociais', 90),
  ('fotografia', 'Pré-casamento', 180),
  ('fotografia', 'Reunião/briefing fotográfico', 60),
  ('aulas-professores-particulares', 'Aula particular', 60),
  ('aulas-professores-particulares', 'Aula experimental', 60),
  ('aulas-professores-particulares', 'Reforço escolar', 60),
  ('aulas-professores-particulares', 'Preparação para provas', 60),
  ('aulas-professores-particulares', 'Preparação para vestibular', 90),
  ('aulas-professores-particulares', 'Preparação para ENEM', 90),
  ('aulas-professores-particulares', 'Aula de idiomas', 60),
  ('aulas-professores-particulares', 'Aula de conversação', 60),
  ('aulas-professores-particulares', 'Aula de matemática', 60),
  ('aulas-professores-particulares', 'Aula de português', 60),
  ('aulas-professores-particulares', 'Aula de física', 60),
  ('aulas-professores-particulares', 'Aula de química', 60),
  ('aulas-professores-particulares', 'Aula de música', 60),
  ('aulas-professores-particulares', 'Aula online', 60),
  ('aulas-professores-particulares', 'Consultoria/aula personalizada', 60);

UPDATE public.service_templates AS st
SET active = false,
    updated_at = now()
WHERE st.business_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM _canonical_service_catalog AS c
    JOIN public.segments AS s ON s.slug = c.segment_slug
    WHERE c.name = st.name AND s.id = st.segment_id
  );

INSERT INTO public.service_templates (
  business_id,
  service_id,
  segment_id,
  name,
  description,
  category,
  price_cents,
  duration_minutes,
  image_url,
  allows_parallel,
  active
)
SELECT
  NULL,
  NULL,
  s.id,
  c.name,
  NULL,
  NULL,
  0,
  c.duration_minutes,
  NULL,
  false,
  true
FROM _canonical_service_catalog AS c
JOIN public.segments AS s ON s.slug = c.segment_slug AND s.active
WHERE NOT EXISTS (
  SELECT 1
  FROM public.service_templates AS st
  WHERE st.business_id IS NULL
    AND st.segment_id = s.id
    AND lower(st.name) = lower(c.name)
);

-- Geral is a compatibility bucket only. New services may remain unsegmented;
-- legacy services continue to retain their existing segment_id.
CREATE OR REPLACE FUNCTION public.assign_default_service_segment()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN NEW;
END;
$$;

COMMIT;
